name: Hello World
run-name: Run by @${{github.actor}}
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      BRAN: main
    steps:
      - uses: actions/checkout@v4
      - run: echo "${BRAN}"
      - run: echo ${{github.actor}}