name: Hello World
run-name: Run by @${{github.actor}}
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      BRAN: main
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: npm install
        if: steps.setup-node.outputs.cache-hit != 'true'
        run: npm ci
      - name: echo react
        run: npm ls