name: Hello World
run-name: Run by @${{github.actor}}
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      BRAN: main
    steps:
      - uses: actions/checkout@v4
      - id: source
        run: echo "${BRAN}" >> "${GITHUB_OUTPUT}"
      - run: echo ${{steps.source.outputs.result}}
      - run: echo ${{github.actor}}